RecoWeb.WebUI/Controllers/LotController.cs
using RecoWeb.Module;
using RecoWeb.Module.Controllers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Web.Mvc;
using RecoWeb.Module.Infrastructure.Concrete;
using DevExtreme.AspNet.Mvc;
using DevExtreme.AspNet.Data;
using Newtonsoft.Json;
using RecoWeb.WebUI.Models.POCO;
using RecoWeb.WebUI.Models;
using RecoWeb.Module.Models.POCO;

namespace RecoWeb.WebUI.Controllers
{
    public class LotController : BaseController
    {
        //2018 07 20 by roy (1) : BaseController에서 하단으로 내려옴
        public ResourceWrapper _resourceManager = new ResourceWrapper();

        private DomainConnectionManager DomainManager;
        public LotController(DomainConnectionManager Domains)
        {
            this.DomainManager = Domains;
        }

        // GET: Lot
        public ActionResult Index()
        {
            return View();
        }

        # region 정전계TreeView(LTM5)
        public ActionResult LTM5()
        {
            var _action = this.Url.RequestContext.RouteData.Values["action"].ToString();
            var _control = this.Url.RequestContext.RouteData.Values["controller"].ToString();
            string _activePage = "";
            if (Session["Menu"] != null)
            {
                _activePage = DomainManager.GetEntityToList<COW_MenuListByJsonInquiry_Result>("COW_MenuListByJsonInquiry", null).Where(s => s.ActionMethod == _action && s.Controller == _control).FirstOrDefault().ParentMenuCode.ToString();
            }
            else
            {
                _activePage = DomainManager.GetEntityToList<COW_MenuListByJsonInquiry_Result>("COW_MenuListByJsonInquiry", null).Where(s => s.ActionMethod == _action && s.Controller == _control).FirstOrDefault().ParentMenuCode.ToString();
            }
            MenuHistory getMenuLocation = new MenuHistory();
            List<string> _menuPage = new List<string>(getMenuLocation.GetMenu(_action, _control, _activePage, DomainManager.GetEntityToList<COW_MenuListByJsonInquiry_Result>("COW_MenuListByJsonInquiry", null).ToList()));

            var plants = DomainManager.GetEntityToList<PRW_PlantInquiry_Result>("PRW_PlantInquiry", null).ToList();
            
            Dapper.DynamicParameters parameters = new Dapper.DynamicParameters();
            parameters.Add("@p_PlantId", plants.FirstOrDefault().PlantId);
            
            Dapper.DynamicParameters parameters02 = new Dapper.DynamicParameters();
            parameters02.Add("@p_EmployeeId", HttpContext.User.Identity.Name);
            parameters02.Add("@p_MenuCode", MethodBase.GetCurrentMethod().Name);
            
            Dapper.DynamicParameters parameters03 = new Dapper.DynamicParameters();
            parameters03.Add("@p_UserId", HttpContext.User.Identity.Name);
            
            Dapper.DynamicParameters parameters04 = new Dapper.DynamicParameters();
            parameters04.Add("@p_PlantId", plants.FirstOrDefault().PlantId);
            
            Dapper.DynamicParameters parameters05 = new Dapper.DynamicParameters();
            parameters05.Add("@p_PlantId", plants.FirstOrDefault().PlantId);
            parameters05.Add("@p_FactoryId", DomainManager.GetEntityToList<COW_FilterFactoriesInquiry_Result>("COW_FilterFactoriesInquiry", parameters04).FirstOrDefault().FactoryId.ToString());
            parameters05.Add("@p_WorkshopTypeId", DomainManager.GetEntityToList<COW_FilterWorkshopTypesInquiry_Result>("COW_FilterWorkshopTypesInquiry", parameters04).FirstOrDefault().WorkshopTypeId.ToString());
            
            LotTraceTreeViewModel viewModel = new LotTraceTreeViewModel
            {
                MenuLocation = _menuPage
                ,
                ActivePage = _activePage
                ,
                resourceManager = _resourceManager
                ,
                PRW_PlantInquiry = DomainManager.GetEntityToList<PRW_PlantInquiry_Result>("PRW_PlantInquiry", null).Where(w => w.IsUse == "Y")
                ,
                //차종 불러오기.
                SMW_CarTypesInquiry = DomainManager.GetEntityToList<SMW_CarTypesInquiry_Result>("SMW_CarTypesInquiry", parameters).ToList()
                ,
                //선택된 plantId
                plantId = plants.FirstOrDefault().PlantId.ToString()
                ,
                startDate = DateTime.Today
                ,
                endDate = DateTime.Today
                ,
                printType = "2"
                ,
                Auth = DomainManager.GetEntityToList<COW_NavMenuAuthorizeInquiry_Result>("COW_NavMenuAuthorizeInquiry", parameters02).ToList().First()
                ,
                COW_FilterPlantInquiry = DomainManager.GetEntityToList<COW_FilterPlantInquiry_Result>("COW_FilterPlantInquiry", parameters03).ToList()
                ,
                COW_FilterFactoriesInquiry = DomainManager.GetEntityToList<COW_FilterFactoriesInquiry_Result>("COW_FilterFactoriesInquiry", parameters04).ToList()
                ,
                COW_FilterWorkshopTypesInquiry = DomainManager.GetEntityToList<COW_FilterWorkshopTypesInquiry_Result>("COW_FilterWorkshopTypesInquiry", parameters04).ToList()
                ,
                COW_FilterWorkshopsInquiry = DomainManager.GetEntityToList<COW_FilterWorkshopsInquiry_Result>("COW_FilterWorkshopsInquiry", parameters05).ToList()
                
            };
            return View(viewModel);
        }



        //[HttpGet]
        public ActionResult GetDataLTW_TraceReverseTreeviewLotInquiry(string p_PlantId, string p_FactoryId, string p_WorkshopTypeId, string p_WorkshopId, string p_WorkDate, string p_PaletteLotId, string p_LotId, string p_PaletteTagId, string p_UserId, DataSourceLoadOptions loadOptions)
        {
            Dapper.DynamicParameters parameters01 = new Dapper.DynamicParameters();
            parameters01.Add("@p_PlantId", p_PlantId);
            parameters01.Add("@p_FactoryId", p_FactoryId);
            parameters01.Add("@p_WorkshopTypeId", p_WorkshopTypeId);
            parameters01.Add("@p_WorkshopId", p_WorkshopId);
            parameters01.Add("@p_WorkDate", p_WorkDate);
            parameters01.Add("@p_PaletteLotId", p_PaletteLotId);
            parameters01.Add("@p_LotId", p_LotId);
            parameters01.Add("@p_PaletteTagId", p_PaletteTagId);
            parameters01.Add("@p_UserId", HttpContext.User.Identity.Name);
            
            var result = DataSourceLoader.Load(DomainManager.GetEntityToList<LTW_TraceReverseTreeviewLotInquiry_Result>("LTW_TraceReverseTreeviewLotInquiry", parameters01), loadOptions);
            var resultJson = JsonConvert.SerializeObject(result);
            return Content(resultJson, "application/json");
            
        }
        
        private static List<LTW_TraceReverseTreeviewInquiry_Result> LTW_TraceReverseTreeviewInquiry = new List<LTW_TraceReverseTreeviewInquiry_Result>();
        private static List<LTW_TraceReverseTreeviewInquiry_Result> LTW_TraceReverseTreeviewInquiryTarget = new List<LTW_TraceReverseTreeviewInquiry_Result>();

        public ActionResult GetDataLTW_TraceReverseTreeviewInquiry(string p_PartId, string p_LotTransId, string p_PaletteLotTransId, DataSourceLoadOptions loadOptions)
        {
            p_PartId = "0";
            Dapper.DynamicParameters parameters01 = new Dapper.DynamicParameters();
            parameters01.Add("@p_PartId", int.Parse(p_PartId));
            parameters01.Add("@p_LotTransId", int.Parse(p_LotTransId));
            parameters01.Add("@p_PaletteLotTransId", int.Parse(p_PaletteLotTransId));
            
            try
            {
                LTW_TraceReverseTreeviewInquiry = DomainManager.GetEntityToList<LTW_TraceReverseTreeviewInquiry_Result>("LTW_TraceReverseTreeviewInquiry", parameters01).ToList();  //repository.LTW_TraceReverseTreeviewInquiry(int.Parse(p_PartId), int.Parse(p_LotTransId), int.Parse(p_PaletteLotTransId)).ToList();
                LTW_TraceReverseTreeviewInquiryTarget = new List<LTW_TraceReverseTreeviewInquiry_Result>();
                LTW_TraceReverseTreeviewInquiry_Result itemRoot = LTW_TraceReverseTreeviewInquiry.Where(x => x.ParentPartId == "0").First();
                LTW_TraceReverseTreeviewInquiryTarget.Add(itemRoot);
                LTW_TraceReverseTreeviewInquiry.Remove(itemRoot);
                GetOrderByList(itemRoot.PartId, ref LTW_TraceReverseTreeviewInquiryTarget);

                var result = DataSourceLoader.Load(LTW_TraceReverseTreeviewInquiryTarget, loadOptions);
                //return Json(LTW_TraceReverseTreeviewInquiryTarget, JsonRequestBehavior.AllowGet);
                var resultJson = JsonConvert.SerializeObject(result);
                return Content(resultJson, "application/json");
            }
            catch (Exception ex)
            {
                return Json(ex.Message, JsonRequestBehavior.AllowGet);
            }
        }

        private static void GetOrderByList(string myKey, ref List<LTW_TraceReverseTreeviewInquiry_Result> lst)
        {
            List<LTW_TraceReverseTreeviewInquiry_Result> listado2 = LTW_TraceReverseTreeviewInquiry.Where(x => x.ParentPartId == myKey).ToList();
            if (listado2.Count > 0)
            {
                foreach (LTW_TraceReverseTreeviewInquiry_Result item in listado2)
                {
                    lst.Add(item);
                    GetOrderByList(item.PartId, ref lst);
                }
            }
        }

        public PartialViewResult AjaxInquiryContextMenu3()
        {
            return PartialView("_LTM5Context");
        }

        #endregion

    }
}

RecoWeb.WebUI/Views/Lot/LTM5.cshtml
@model RecoWeb.WebUI.Models.LotTraceTreeViewModel
@using RecoWeb.Domain.LocalResource

@{

    AjaxOptions ajaxInquiry = new AjaxOptions
    {
        HttpMethod = "GET",
        InsertionMode = InsertionMode.Replace,
        OnSuccess = "ContextInquiry",
        UpdateTargetId = "Context"

    };
}

@* 화면의 조회조건이 표현되는 영역 *@
@using (Ajax.BeginForm("AjaxInquiryContextMenu3", "Lot", ajaxInquiry))
{
    <div class="row wrapper white-bg page-heading">
        <div class="col-lg-8 col-md-8 col-xs-12" style="display:flex;">
            <span style="float:left; padding:0.6rem; font-size:14px;">
                <i class="fa fa-th" aria-hidden="true"></i>
            </span>
            <div style="align-self:flex-end; padding:0.6rem">

                <ol class="breadcrumb" style="font-size:14px;">
                    @foreach (var page in Model.MenuLocation)
                    {
                        if (page == Model.ActivePage)
                        {
                            <li class="active">
                                <strong>@Model.resourceManager.String("Menu_" + @page) </strong>
                            </li>
                        }
                        else
                        {
                            <li>
                                <span>@Model.resourceManager.String("Menu_" + @page)</span>
                            </li>
                        }
                    }
                </ol>
            </div>
        </div>
        <div class="col-lg-4 col-md-4">
            <div class="btn-group pull-right ">
                <button class="btn bg-primary" type="submit" id="btn-find"><i class="fa fa-check"></i>&nbsp;@Resource.Inquiry</button>
            </div>
        </div>
    </div>
    <div class="row wrapper border-bottom white-bg check-item">
        <div class="btn-group">
            <span class="mr-3">
                <label class="filter-title mr-1">플랜트:</label>
                @Html.DropDownListFor(x => x.COW_FilterPlantInquiry.FirstOrDefault().PlantName,
                                        new SelectList(Model.COW_FilterPlantInquiry.Select(s => new SelectListItem { Value = s.PlantId, Text = s.PlantName }), "Value", "Text")
                                        , new { @class = "reco-width-M filter-item", @id = "Plants" })
            </span>
            <span class="mr-3">
                <label class="filter-title mr-1">공장동:</label>
                @Html.DropDownListFor(x => x.COW_FilterFactoriesInquiry.FirstOrDefault().FactoryName,
                                        new SelectList(Model.COW_FilterFactoriesInquiry.Select(s => new SelectListItem { Value = s.FactoryId, Text = s.FactoryName }), "Value", "Text")
                                        , new { @class = "reco-width-M filter-item", @id = "Factories" })
            </span>
            <span class="mr-3">
                <label class="filter-title mr-1">작업유형:</label>
                @Html.DropDownListFor(x => x.COW_FilterWorkshopTypesInquiry.FirstOrDefault().Desc,
                                        new SelectList(Model.COW_FilterWorkshopTypesInquiry.Select(s => new SelectListItem { Value = s.WorkshopTypeId, Text = s.Desc }), "Value", "Text")
                                        , new { @class = "reco-width-M filter-item", @id = "WorkshopTypes" })
            </span>
            <span class="mr-3">
                <label class="filter-title mr-1">작업장리스트:</label>
                @Html.DropDownListFor(x => x.COW_FilterWorkshopsInquiry.FirstOrDefault().WorkshopName,
                                        new SelectList(Model.COW_FilterWorkshopsInquiry.Select(s => new SelectListItem { Value = s.WorkshopCode, Text = s.WorkshopName }), "Value", "Text")
                                        , new { @class = "reco-width-M filter-item", @id = "Workshops" })
            </span>
            <span class="mr-3">
                @*현재 날짜를 둘다 받아옴. 여기서 날짜를 컨트롤하고싶다면 Controller에서 날짜 지정해서 넘겨주면됨.*@
                <label class="filter-title mr-1">일자:</label>
                @Html.TextBoxFor(m => m.startDate, "{0:yyyy-MM-dd}", new { @class = "reco-width_XL datepicker filter-item", @data_date_format = "yyyy-mm-dd", @style = "z-index:100; border:solid #A9A9A9 1px;" })
            </span>
            <br />
            <span class="mr-3">
                <label class="filter-title mr-1">팔레트LOT:</label>
                <input type="text" name="PaletteLotNo" id="PaletteLotNo" value="" class="filter-item" />
            </span>
            <span class="mr-3">
                <label class="filter-title mr-1">LOT NO:</label>
                <input type="text" name="LotNo" id="LotNo" value="" class="filter-item"/>
            </span>
            <span class="mr-3">
                <label class="filter-title mr-1">RF태그번호:</label>
                <input type="text" name="RfTagNo" id="RfTagNo" value="" class="filter-item" />
            </span>
        </div>
    </div>

}

@* View파일이 너무 길어져 소스가 보기 어려워져 Partial로 실제 데이터가 나타나는 부분을 따로 분리 *@
<div id="Context" class="row wrapper wrapper-content animated fadeInRight">
    @Html.Partial("_LTM5Context")
</div>


@section Styles {
    
}

@section Scripts {
    <script src="~/Scripts/jquery-3.1.1.min.js"></script>

    <script type="text/javascript">
        var data2;
        function ContextInquiry(returnValue) {
            var data = returnValue;
            data2 = returnValue;
        }

        $(document).ready(function () {

            $(':input:checked').parent('.btn').addClass('active');

            // Dropdown list change event.
            // Dropdown list change event.
            $('#Plants').change(function () {
                $('#Factories option').remove();
                $('#WorkshopTypes option').remove();
                $('#Workshops option').remove();
                $.getJSON('../Common/GetCOW_FilterFactoriesInquiry', { p_PlantId: $('#Plants').val() }, function (data) {
                    $.each(data, function () {
                        $('#Factories').append('<option value=' +
                          this.FactoryId + '>' + this.FactoryName + '</option>');
                    });

                }).fail(function (jqXHR, textStatus, errorThrown) {
                    alert('Error getting products!');
                });

                $.getJSON('../Common/GetCOW_FilterWorkshopTypesInquiry', { p_PlantId: $('#Plants').val() }, function (data) {
                    $.each(data, function () {
                        $('#WorkshopTypes').append('<option value=' +
                          this.WorkshopTypeId + '>' + this.Desc + '</option>');
                    });

                }).fail(function (jqXHR, textStatus, errorThrown) {
                    alert('Error getting products!');
                });

                $.getJSON('../Common/GetCOW_FilterWorkshopsInquiry', { p_PlantId: $('#Plants').val(), p_FactoryId: $('#Factories').val(), p_WorkshopTypeId: $('#WorkshopTypes').val() }, function (data) {
                    $.each(data, function () {
                        $('#Workshops').append('<option value=' +
                          this.WorkshopId + '>' + this.WorkshopName + '</option>');
                    });

                }).fail(function (jqXHR, textStatus, errorThrown) {
                    alert('Error getting products!');
                });

            });

            $('#Factories').change(function () {
                $('#Workshops option').remove();
                $.getJSON('../Common/GetCOW_FilterWorkshopsInquiry', { p_PlantId: $('#Plants').val(), p_FactoryId: $('#Factories').val(), p_WorkshopTypeId: $('#WorkshopTypes').val() }, function (data) {
                    $.each(data, function () {
                        $('#Workshops').append('<option value=' +
                          this.WorkshopId + '>' + this.WorkshopName + '</option>');
                    });

                }).fail(function (jqXHR, textStatus, errorThrown) {
                    alert('Error getting products!');
                });
            });

            $('#WorkshopTypes').change(function () {
                $('#Workshops option').remove();
                $.getJSON('../Common/GetCOW_FilterWorkshopsInquiry', { p_PlantId: $('#Plants').val(), p_FactoryId: $('#Factories').val(), p_WorkshopTypeId: $('#WorkshopTypes').val() }, function (data) {
                    $.each(data, function () {
                        $('#Workshops').append('<option value=' +
                          this.WorkshopId + '>' + this.WorkshopName + '</option>');
                    });

                }).fail(function (jqXHR, textStatus, errorThrown) {
                    alert('Error getting products!');
                });
            });

            //showGrid1();

            $('.datepicker').datepicker({
                language: 'ko'
                , autoclose: true
            });
        });
    </script>
}

RecoWeb.WebUI/Views/Lot/_LTM5Context.cshtml
@using RecoWeb.Domain.LocalResource

<div class="col-lg-5 col-md-5 h-100">
    <div class="ibox">
        <div class="ibox-title">
            <span style="font-size:1.4rem;"><i class="fa fa-list-alt" aria-hidden="true"></i>&nbsp;LOT리스트</span>
        </div>
        <div class="ibox-content">
            <div id="data-grid-demo">
                @(Html.DevExtreme().DataGrid()
                .ID("gridContainer01")
                .Paging(paging => paging.PageSize(20))
                .Pager(pager =>
                {
                    pager.ShowPageSizeSelector(true);
                    pager.AllowedPageSizes(new List<int>
                    { 20, 50, 100, 200, 300, 500 });
                    pager.ShowInfo(true);
                })
                    .Export(e => e.Enabled(true).FileName("ExportTest").AllowExportSelectedData(true))
                    .ColumnAutoWidth(true)
                    .ShowColumnLines(true)
                    .ShowRowLines(true)
                    .ShowBorders(true)
                    .OnContentReady("onReady") // 레디 이벤트
                    .HoverStateEnabled(true)
                    .Sorting(e => e.Mode(GridSortingMode.Multiple))
                    .ColumnMinWidth(50)
                    .AllowColumnResizing(true)
                    .Option("columnResizingMode", ColumnResizingMode.Widget)
                    //칼럼이름의 시작에 !, @, -, _를 붙이면 _로 바뀜
                    .DataSource(ds => ds.Mvc().Controller("Lot").Key("_KeyColumn")
                    .LoadAction("GetDataLTW_TraceReverseTreeviewLotInquiry")
                    .LoadParams(new
                    {
                        p_PlantId = new JS("getIdValue('Plants')")
                    ,
                        p_FactoryId = new JS("getIdValue('Factories')")
                    ,
                        p_WorkshopTypeId = new JS("getIdValue('WorkshopTypes')")
                    ,
                        p_WorkshopId = new JS("getIdValue('Workshops')")
                    ,
                        p_WorkDate = new JS("getIdValue('startDate')")
                    ,
                        p_PaletteLotId = new JS("getIdValue('PaletteLotNo')")
                    ,
                        p_LotId = new JS("getIdValue('LotNo')")
                    ,
                        p_PaletteTagId = new JS("getIdValue('RfTagNo')")
                    ,
                        p_UserId = ""
                    })
                    )
                    .Columns(columns =>
                    {
                        columns.Add().DataField("WorkDate").Caption("작업일").Alignment(HorizontalAlignment.Center);
                        columns.Add().DataField("PartCode").Caption("품번").Alignment(HorizontalAlignment.Left);
                        columns.Add().DataField("Palette_Lot").Caption("팔레트LOT").Alignment(HorizontalAlignment.Left);
                        columns.Add().DataField("Lot").Caption("LOT").Alignment(HorizontalAlignment.Center);
                        columns.Add().DataField("Palette_Tag").Caption("팔래트태그").Alignment(HorizontalAlignment.Center);
                        columns.Add().DataField("WorkshopName").Caption("작업장명").Alignment(HorizontalAlignment.Left).Visible(false);
                        columns.Add().DataField("_IsMetalPrint").Caption("출력유무").Alignment(HorizontalAlignment.Left).Visible(false);
                        columns.Add().DataField("_PaletteTagId").Caption("팔레트태그아디").Alignment(HorizontalAlignment.Left).Visible(false);
                        columns.Add().DataField("_PartId").Caption("품번아디").Alignment(HorizontalAlignment.Left).Visible(false);
                        columns.Add().DataField("_LotTransId").Caption("LOT트랜스").Alignment(HorizontalAlignment.Left).Visible(false);
                        columns.Add().DataField("_PaletteLotTransId").Caption("팔레트트랜스").Alignment(HorizontalAlignment.Left).Visible(false);
                        columns.Add().DataField("_KeyColumn").Caption("키").Alignment(HorizontalAlignment.Left).Visible(false);
                        columns.Add().DataField("_PARAM").Caption("파라미터").Alignment(HorizontalAlignment.Left).Visible(false);
                    })
                    .OnSelectionChanged("grid1Change") //체인지 이벤트를 선언함
                    .Height(new JS("heightCalc(' 100')"))
                    .Selection(e =>
                    e.Mode(SelectionMode.Single))
                )


                @*<table id="TCI-Grid1" cellpadding="0" cellspacing="0"></table>
                <div id="TCI-Pager1" style="text-align: center;">
                </div>*@
            </div>
        </div>
    </div>
</div>

<div class="col-lg-7 col-md-7 h-100">
    <div>
        <div class="ibox">
            <div class="ibox-title">
                <span style="font-size:1.4rem;"><i class="fa fa-list-ul" aria-hidden="true"></i>&nbsp;LOT트리뷰</span>
            </div>
            <div class="ibox-content">
                @(Html.DevExtreme().TreeList()
                    .ID("gridContainer02")
                    .KeyExpr("PartId")
                    .ParentIdExpr("ParentPartId")
                    .Columns(columns =>
                    {
                        columns.Add().DataField("PartCode").Caption("품번").Alignment(HorizontalAlignment.Left);
                        columns.Add().DataField("PartName").Caption("품명").Alignment(HorizontalAlignment.Left);
                        columns.Add().DataField("LotId").Caption("LOT").Alignment(HorizontalAlignment.Left);
                        columns.Add().DataField("LotQty").Caption("수량").Alignment(HorizontalAlignment.Right);
                        columns.Add().DataField("PartTypeName").Caption("종류").Alignment(HorizontalAlignment.Center);

                        columns.Add().DataField("WorkDate").Caption("WorkDate").Visible(false);
                        columns.Add().DataField("InputTime").Caption("InputTime").Visible(false);
                        columns.Add().DataField("DelvTime").Caption("DelvTime").Visible(false);
                    })
                    .ShowRowLines(true)
                    .ShowColumnLines(true)
                    .ShowBorders(true)
                    .ColumnAutoWidth(true)
                    .ExpandedRowKeys(new[] { 1 })
                    .HoverStateEnabled(true)
                    .Selection(e =>e.Mode(SelectionMode.Single))
                )
            </div>
        </div>
    </div>


</div>


<script type="text/javascript">
    //그리드 Load이후 타는 이벤트
    function onReady(a) {
        if ($('#gridContainer01').dxDataGrid("instance").totalCount() > 0) {
            $('#gridContainer01').dxDataGrid("instance").selectRowsByIndexes(0);
            //↑ 동일함. (↓더 많은 테스트는 진행못함)
            //$('#' + a.element[0].id).dxDataGrid("instance").selectRows(1)
        }
    }
    var akjvna;
    function grid1Change(selectedRow) {
        try {
            akjvna = selectedRow;
            var orders = new DevExpress.data.CustomStore({
                load: function (loadOptions) {
                    var deferred = $.Deferred(),
                        args = {};

                    if (loadOptions.sort) {
                        args.orderby = loadOptions.sort[0].selector;
                        if (loadOptions.sort[0].desc)
                            args.orderby += " desc";
                    }

                    $.ajax({
                        url: "../Lot/GetDataLTW_TraceReverseTreeviewInquiry?p_PartId=" + selectedRow.selectedRowsData[0]._PartId + "&p_LotTransId=" + selectedRow.selectedRowsData[0]._LotTransId + "&p_PaletteLotTransId=" + selectedRow.selectedRowsData[0]._PaletteLotTransId,
                        dataType: "json",
                        data: args,
                        success: function (result) {
                            deferred.resolve(result.data);
                            a = result;
                            console.log(result.data);
                        },
                        error: function (e) {
                            console.log("onReadyError");
                            console.log(e);
                            deferred.reject("Data Loading Error");
                        },
                        timeout: 10000
                    });
                    return deferred.promise();
                }
            });
            $("#gridContainer02").dxTreeList({
                dataSource: {
                    store: orders
                }
            }).dxTreeList("instance").refresh();
        }
        catch (e) {
            console.log(e);
        }
    }   

</script>