RecoWeb.WebUI/Controllers/ProductionController.cs
using RecoWeb.Domain.Concrete;
using RecoWeb.Module;
using RecoWeb.Module.Controllers;
using RecoWeb.Module.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Reflection;
using System.Web.Mvc;
using RecoWeb.Module.Infrastructure.Concrete;
using DevExtreme.AspNet.Mvc;
using DevExtreme.AspNet.Data;
using Newtonsoft.Json;
using System.Data.Entity.Core.Objects;
using RecoWeb.WebUI.Models.POCO;
using RecoWeb.Module.Models.POCO;
using RecoWeb.WebUI.Models;

namespace RecoWeb.WebUI.Controllers
{
    public class ProductionController : BaseController
    {

        //2018 07 20 by roy (1) : BaseController에서 하단으로 내려옴
        public ResourceWrapper _resourceManager = new ResourceWrapper();

        private DomainConnectionManager DomainManager;
        public ProductionController(DomainConnectionManager Domains)
        {
            this.DomainManager = Domains;
        }


        // GET: Production
        public ActionResult Index()
        {
            return View();
        }

        #region 비가동Top10
        public PartialViewResult DowntimeTop100ContextMenu()
        {

            return PartialView("_PNS3Context");
        }

        public ActionResult PNS3()
        {
            var _action = this.Url.RequestContext.RouteData.Values["action"].ToString();
            var _control = this.Url.RequestContext.RouteData.Values["controller"].ToString();
            string _activePage = "";
            if (Session["Menu"] != null)
            {
                _activePage = DomainManager.GetEntityToList<COW_MenuListByJsonInquiry_Result>("COW_MenuListByJsonInquiry", null).Where(s => s.ActionMethod == _action && s.Controller == _control).FirstOrDefault().ParentMenuCode.ToString();
            }
            else
            {
                _activePage = DomainManager.GetEntityToList<COW_MenuListByJsonInquiry_Result>("COW_MenuListByJsonInquiry", null).Where(s => s.ActionMethod == _action && s.Controller == _control).FirstOrDefault().ParentMenuCode.ToString();
            }

            MenuHistory getMenuLocation = new MenuHistory();
            List<string> _menuPage = new List<string>(getMenuLocation.GetMenu(_action, _control, _activePage, DomainManager.GetEntityToList<COW_MenuListByJsonInquiry_Result>("COW_MenuListByJsonInquiry", null).ToList()));
            
            Dapper.DynamicParameters parameters00 = new Dapper.DynamicParameters();
            parameters00.Add("@p_UserId", HttpContext.User.Identity.Name);

            var plants = DomainManager.GetEntityToList<COW_FilterPlantInquiry_Result>("COW_FilterPlantInquiry", parameters00).ToList();
            
            Dapper.DynamicParameters parameters01 = new Dapper.DynamicParameters();
            parameters01.Add("@p_PlantId", plants.FirstOrDefault().PlantId);
            
            Dapper.DynamicParameters parameters02 = new Dapper.DynamicParameters();
            parameters02.Add("@p_EmployeeId", HttpContext.User.Identity.Name);
            parameters02.Add("@p_MenuCode", MethodBase.GetCurrentMethod().Name);
            
            var factory = DomainManager.GetEntityToList<COW_FilterFactoriesInquiry_Result>("COW_FilterFactoriesInquiry", parameters01).ToList();
            var workType = DomainManager.GetEntityToList<COW_FilterWorkshopTypesInquiry_Result>("COW_FilterWorkshopTypesInquiry", parameters01).ToList();

            Dapper.DynamicParameters parameters05 = new Dapper.DynamicParameters();
            parameters05.Add("@p_PlantId", plants.FirstOrDefault().PlantId);
            parameters05.Add("@p_FactoryId", factory.FirstOrDefault().FactoryId);
            parameters05.Add("@p_WorkshopTypeId", workType.FirstOrDefault().WorkshopTypeId);
            
            PRW_NotworkTop10ViewModel viewModel = new PRW_NotworkTop10ViewModel
            {
                MenuLocation = _menuPage
                ,
                ActivePage = _activePage
                ,
                resourceManager = _resourceManager
                ,
                PRW_PlantInquiry = DomainManager.GetEntityToList<PRW_PlantInquiry_Result>("PRW_PlantInquiry", null).Where(w => w.IsUse == "Y") //repository.PRW_PlantInquiry().Where(w => w.IsUse == "Y")
                ,
                //차종 불러오기.
                SMW_CarTypesInquiry = DomainManager.GetEntityToList<SMW_CarTypesInquiry_Result>("SMW_CarTypesInquiry", parameters01).ToList()  // repository.SMW_CarTypesInquiry(repository.PRW_PlantInquiry().FirstOrDefault().PlantId.ToString()).ToList()
                ,
                //선택된 plantId
                plantId = plants.FirstOrDefault().PlantId //DomainManager.GetEntityToList<>("PRW_PlantInquiry", null).Cast<PRW_PlantInquiry_Result>().FirstOrDefault().PlantId.ToString() // repository.PRW_PlantInquiry().FirstOrDefault().PlantId.ToString()
                ,
                startDate = DateTime.Today
                ,
                endDate = DateTime.Today
                ,
                Auth = DomainManager.GetEntityToList<COW_NavMenuAuthorizeInquiry_Result>("COW_NavMenuAuthorizeInquiry", parameters02).ToList().First() // repository.COW_NavMenuAuthorizeInquiry(HttpContext.User.Identity.Name, MethodBase.GetCurrentMethod().Name).ToList().First()
                ,
                COW_FilterPlantInquiry = plants.ToList()
                ,
                COW_FilterFactoriesAllInquiry = DomainManager.GetEntityToList<COW_FilterFactoriesAllInquiry_Result>("COW_FilterFactoriesAllInquiry", parameters01).ToList() // repository.COW_FilterFactoriesAllInquiry(repository.COW_FilterPlantInquiry(HttpContext.User.Identity.Name).FirstOrDefault().PlantId.ToString()).ToList()
                ,
                COW_FilterWorkshopTypesAllInquiry = DomainManager.GetEntityToList<COW_FilterWorkshopTypesAllInquiry_Result>("COW_FilterWorkshopTypesAllInquiry", parameters01).ToList()    //repository.COW_FilterWorkshopTypesAllInquiry(repository.COW_FilterPlantInquiry(HttpContext.User.Identity.Name).FirstOrDefault().PlantId.ToString()).ToList()
                ,
                COW_FilterWorkshopsAllInquiry = DomainManager.GetEntityToList<COW_FilterWorkshopsAllInquiry_Result>("COW_FilterWorkshopsAllInquiry", parameters05).ToList()
                ,
                Gubun2 = "D" //일간:D,주간:W,월간:M
                ,
                Gubun1 = "W" //라인:W,비가동:D
            };

            return View(viewModel);

        }

        //[HttpGet]
        public ActionResult GetDowntimeTop10Result(string p_PlantId, string p_FactoryId, string p_WorkshopTypeId, string p_WorkshopId, string p_WorkDate, string p_Gubun1, string p_Gubun2, DataSourceLoadOptions loadOptions)
        {
            try
            {
                Dapper.DynamicParameters parameters01 = new Dapper.DynamicParameters();
                parameters01.Add("@p_PlantId", p_PlantId);
                parameters01.Add("@p_FactoriesId", p_FactoryId);
                parameters01.Add("@p_WorkshopTypeId", p_WorkshopTypeId);
                parameters01.Add("@p_WorkshopId", p_WorkshopId);
                parameters01.Add("@p_StandardDate", p_WorkDate);
                parameters01.Add("@p_Section", p_Gubun1);
                parameters01.Add("@p_Period", p_Gubun2);
                
                var result = DataSourceLoader.Load(DomainManager.GetEntityToList<PRW_DowntimeHistoryTop10Inquiry_Result>("PRW_DowntimeHistoryTop10Inquiry", parameters01), loadOptions);
                var resultJson = JsonConvert.SerializeObject(result);
                return Content(resultJson, "application/json");
            }
            catch (Exception ex)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json(new { Message = ex.Message.ToString() });
            }
        }

        //그리드 불러오는 곳인데, 주석 쳐놓은게 기존에 쓰던것임..
        //어떻게 불러와야할지 몰라서 둘다 두긴함..
        //기존 반환 형식 : JsonResult
        //Extreme 반환 형식 : ActionResult
        public ActionResult GetDowntimeTop10ChartResult(string p_PlantId, string p_FactoryId, string p_WorkshopTypeId, string p_WorkshopId, string p_WorkDate, string p_Gubun1, string p_Gubun2, DataSourceLoadOptions loadOptions)
        {
            Dapper.DynamicParameters parameters01 = new Dapper.DynamicParameters();
            parameters01.Add("@p_PlantId", p_PlantId);
            parameters01.Add("@p_FactoriesId", p_FactoryId);
            parameters01.Add("@p_WorkshopTypeId", p_WorkshopTypeId);
            parameters01.Add("@p_WorkshopId", p_WorkshopId);
            parameters01.Add("@p_StandardDate", p_WorkDate);
            parameters01.Add("@p_Section", p_Gubun1);
            parameters01.Add("@p_Period", p_Gubun2);

            var result = DataSourceLoader.Load(DomainManager.GetEntityToList<PRW_DowntimeHistoryTop10Chart1Inquiry_Result>("PRW_DowntimeHistoryTop10Chart1Inquiry", parameters01), loadOptions);
            var resultJson = JsonConvert.SerializeObject(result);
            return Content(resultJson, "application/json");
        }
        
        #endregion
    }
}

RecoWeb.WebUI/Views/Production/PNS3.cshtml
@model RecoWeb.WebUI.Models.PRW_NotworkTop10ViewModel
@using RecoWeb.Domain.LocalResource

@{
    AjaxOptions ajaxInquiry = new AjaxOptions
    {
        HttpMethod = "GET",
        InsertionMode = InsertionMode.Replace,
        OnSuccess = "ContextInquiry",
        UpdateTargetId = "Context"

    };
}
@*actionName을 가지고 AjaxInquiryContextMenu에
        파라미터로 넘겨주고 비교해 불러올 partialView를 선택하고싶었습니다..T-T 아래와 같은 파라미터를 써서..
    , new { ccc = "SIS" }*@
@using (Ajax.BeginForm("DowntimeTop100ContextMenu", "Production", ajaxInquiry))
{
    <div class="row wrapper white-bg page-heading">
        <div class="col-lg-8 col-md-8 col-xs-12" style="display:flex;">
            <span style="float:left; padding:0.6rem; font-size:14px;">
                <i class="fa fa-th" aria-hidden="true"></i>
            </span>
            <div style="align-self:flex-end; padding:0.6rem">

                <ol class="breadcrumb" style="font-size:14px;">
                    @foreach (var page in Model.MenuLocation)
                    {
                        if (page == Model.ActivePage)
                        {
                            <li class="active">
                                <strong>@Model.resourceManager.String("Menu_" + @page) </strong>
                            </li>
                        }
                        else
                        {
                            <li>
                                <span>@Model.resourceManager.String("Menu_" + @page)</span>
                            </li>
                        }
                    }
                </ol>
            </div>
        </div>
        <div class="col-lg-4 col-md-4">
            <div class="btn-group pull-right ">
                @*<button class="btn bg-primary" type="submit" id="btn-find1"><i class="fa fa-check"></i>&nbsp;@Resource.Inquiry</button>*@
                <button class="btn bg-primary" type="submit" id="btn-find"><i class="fa fa-check"></i>&nbsp;@Resource.Inquiry</button>
            </div>
        </div>
    </div>
    <div class="row wrapper border-bottom white-bg check-item">
        <div class="btn-group">
            <span class="mr-3">
                <label class="filter-title mr-1">플랜트:</label>
                @Html.DropDownListFor(x => x.COW_FilterPlantInquiry.FirstOrDefault().PlantName,
                                        new SelectList(Model.COW_FilterPlantInquiry.Select(s => new SelectListItem { Value = s.PlantId, Text = s.PlantName }), "Value", "Text")
                                        , new { @class = "reco-width-M filter-item", @id = "Plants" })
            </span>
            <span class="mr-3">
                <label class="filter-title mr-1">공장동:</label>
                @Html.DropDownListFor(x => x.COW_FilterFactoriesAllInquiry.FirstOrDefault().FactoryName,
                                        new SelectList(Model.COW_FilterFactoriesAllInquiry.Select(s => new SelectListItem { Value = s.FactoryId, Text = s.FactoryName }), "Value", "Text")
                                        , new { @class = "reco-width-M filter-item", @id = "Factories" })
            </span>
            <span class="mr-3">
                <label class="filter-title mr-1">작업유형:</label>
                @Html.DropDownListFor(x => x.COW_FilterWorkshopTypesAllInquiry.FirstOrDefault().Desc,
                                        new SelectList(Model.COW_FilterWorkshopTypesAllInquiry.Select(s => new SelectListItem { Value = s.WorkshopTypeId, Text = s.Desc }), "Value", "Text")
                                        , new { @class = "reco-width-M filter-item", @id = "WorkshopTypes" })
            </span>
            <span class="mr-3">
                <label class="filter-title mr-1">작업장리스트:</label>
                @Html.DropDownListFor(x => x.COW_FilterWorkshopsAllInquiry.FirstOrDefault().WorkshopName,
                                        new SelectList(Model.COW_FilterWorkshopsAllInquiry.Select(s => new SelectListItem { Value = s.WorkshopCode, Text = s.WorkshopName }), "Value", "Text")
                                        , new { @class = "reco-width-M filter-item", @id = "Workshops" })
            </span>
            <span class="mr-3">
                @*현재 날짜를 둘다 받아옴. 여기서 날짜를 컨트롤하고싶다면 Controller에서 날짜 지정해서 넘겨주면됨.*@
                <label class="filter-title mr-1">일자:</label>
                @Html.TextBoxFor(m => m.startDate, "{0:yyyy-MM-dd}", new { @class = "reco-width_XL datepicker", @data_date_format = "yyyy-mm-dd", @style = "z-index:100; border:solid #A9A9A9 1px;" })
            </span>
            <span class="mr-3">
                <label class="filter-title mr-1">구분1:</label>
                <div class="btn-group radios" data-toggle="buttons" style="float:none; margin-bottom:5px;">
                    @Html.RadioButtonFor(x => x.Gubun1, Model.Gubun1 == "W" ? "W" : "W", new { @class = (Model.Gubun1 == "W" ? "checked=Checked filter-item" : "") })라인
                    @Html.RadioButtonFor(x => x.Gubun1, Model.Gubun1 == "D" ? "D" : "D", new { @class = (Model.Gubun1 == "D" ? "checked=Checked filter-item" : "") })불량
                </div>
            </span>

            <span class="mr-3">
                <label class="filter-title mr-1">구분2:</label>
                <div class="btn-group radios" data-toggle="buttons" style="float:none; margin-bottom:5px;">
                    @Html.RadioButtonFor(x => x.Gubun2, Model.Gubun2 == "D" ? "D" : "D", new { @class = (Model.Gubun2 == "D" ? "checked=Checked filter-item" : "") })일간
                    @Html.RadioButtonFor(x => x.Gubun2, Model.Gubun2 == "W" ? "W" : "W", new { @class = (Model.Gubun2 == "W" ? "checked=Checked filter-item" : "") })주간
                    @Html.RadioButtonFor(x => x.Gubun2, Model.Gubun2 == "M" ? "M" : "M", new { @class = (Model.Gubun2 == "M" ? "checked=Checked filter-item" : "") })월간
                </div>
            </span>
        </div>
    </div>


}
<div id="Context" class="row wrapper wrapper-content animated fadeInRight">
    @Html.Partial("_PNS3Context")
</div>


@section Styles {
    @*@Styles.Render("~/Content/plugins/jqGrid/jqGridStyles")
    @Styles.Render("~/plugins/morrisStyles")*@
}

@section Scripts {
    <script src="~/Scripts/jquery-3.1.1.min.js"></script>
    @Scripts.Render("~/plugins/fileSaver")
    @Scripts.Render("~/plugins/dom-to-image")
    @Scripts.Render("~/plugins/sheetJs")
    @Scripts.Render("~/plugins/lightboxGallery")
    @Scripts.Render("~/plugins/sweetAlert")
    @Scripts.Render("~/plugins/html2canvas")
    @Scripts.Render("~/plugins/es6-promise")


    <script type="text/javascript">

        function ContextInquiry(returnValue) {
            var data = returnValue;
        }

        var chkcell = { cellId: undefined, chkval: undefined }; //cell rowspan 중복 체크

        //셀 Merge
        //첫 셀을 제외하고 나머지 중복되는 셀은 display=none해줌.
        function CellMerge(rowid, val, rowObject, cm, rdata) {
            var result;

            if (chkcell.chkval != val) {
                //check 값이랑 비교값이 다른 경우
                var cellId = this.id + '_row_' + rowObject.DPDate;
                result = ' rowspan="1" id ="' + cellId + '" + name="cellRowspan" style="background-color:#DCE6F1;font-size:1.2rem;font-weight: bold"';
                chkcell = { cellId: cellId, chkval: val };
            } else {
                //같을 경우 display none 처리
                result = 'style="display:none"  rowspanid="' + chkcell.cellId + '"';
            }
            return result;
        }
        //값이 0인지 체크하고 백그라운드 변경해줌.
        function CellZeroCheck(rowid, val, rowObject, cm, rdata) {
            var result = "";
            if (val == 0) {

                result = 'style="background-color:#D9D9D9;';
            }
            return result;
        }


        $(document).ready(function () {
            $(':input:checked').parent('.btn').addClass('active');

            // Dropdown list change event.
            // Dropdown list change event.
            $('#Plants').change(function () {
                $('#Factories option').remove();
                $('#WorkshopTypes option').remove();
                $('#Workshops option').remove();
                $.getJSON('../Common/GetCOW_FilterFactoriesAllInquiry', { p_PlantId: $('#Plants').val() }, function (data) {
                    $.each(data, function () {
                        $('#Factories').append('<option value=' +
                          this.FactoryId + '>' + this.FactoryName + '</option>');
                    });

                }).fail(function (jqXHR, textStatus, errorThrown) {
                    alert('Error getting products!');
                });

                $.getJSON('../Common/GetCOW_FilterWorkshopTypesAllInquiry', { p_PlantId: $('#Plants').val() }, function (data) {
                    $.each(data, function () {
                        $('#WorkshopTypes').append('<option value=' +
                          this.WorkshopTypeId + '>' + this.Desc + '</option>');
                    });

                }).fail(function (jqXHR, textStatus, errorThrown) {
                    alert('Error getting products!');
                });

                $.getJSON('../Common/GetCOW_FilterWorkshopsAllInquiry', { p_PlantId: $('#Plants').val(), p_FactoryId: $('#Factories').val(), p_WorkshopTypeId: $('#WorkshopTypes').val() }, function (data) {
                    $.each(data, function () {
                        $('#Workshops').append('<option value=' +
                          this.WorkshopId + '>' + this.WorkshopName + '</option>');
                    });

                }).fail(function (jqXHR, textStatus, errorThrown) {
                    alert('Error getting products!');
                });

            });

            $('#Factories').change(function () {
                $('#Workshops option').remove();
                $.getJSON('../Common/GetCOW_FilterWorkshopsAllInquiry', { p_PlantId: $('#Plants').val(), p_FactoryId: $('#Factories').val(), p_WorkshopTypeId: $('#WorkshopTypes').val() }, function (data) {
                    $.each(data, function () {
                        $('#Workshops').append('<option value=' +
                          this.WorkshopId + '>' + this.WorkshopName + '</option>');
                    });

                }).fail(function (jqXHR, textStatus, errorThrown) {
                    alert('Error getting products!');
                });
            });

            $('#WorkshopTypes').change(function () {
                $('#Workshops option').remove();
                $.getJSON('../Common/GetCOW_FilterWorkshopsAllInquiry', { p_PlantId: $('#Plants').val(), p_FactoryId: $('#Factories').val(), p_WorkshopTypeId: $('#WorkshopTypes').val() }, function (data) {
                    $.each(data, function () {
                        $('#Workshops').append('<option value=' +
                          this.WorkshopId + '>' + this.WorkshopName + '</option>');
                    });

                }).fail(function (jqXHR, textStatus, errorThrown) {
                    alert('Error getting products!');
                });
            });

            $('.datepicker').datepicker({
                language: 'ko'
                , autoclose: true
            });
        });
    </script>
}

<script src="~/Scripts/plugins/morris/xeponline.jqplugin.js"></script>