RecoWeb.WebUI/Controllers/DeliveryController.cs
using DevExtreme.AspNet.Data;
using DevExtreme.AspNet.Mvc;
using Newtonsoft.Json;
using RecoWeb.Module;
using RecoWeb.Module.Controllers;
using RecoWeb.Module.Infrastructure.Concrete;
using RecoWeb.Module.Models.POCO;
using RecoWeb.WebUI.Models;
using RecoWeb.WebUI.Models.POCO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace RecoWeb.WebUI.Controllers
{
    public class DeliveryController : BaseController
    {
        //2018 07 20 by roy (1) : BaseController에서 하단으로 내려옴
        public ResourceWrapper _resourceManager = new ResourceWrapper();

        private DomainConnectionManager DomainManager;
        public DeliveryController(DomainConnectionManager Domains)
        {
            this.DomainManager = Domains;
        }

        // GET: Delivery
        public ActionResult Index()
        {
            return View();
        }


        #region 서열정보 집계(DYP5)
        public PartialViewResult AjaxInquiryContextMenu()
        {
            return PartialView("_DYP5Context");
        }
        public ActionResult DYP5()
        {
            var _action = this.Url.RequestContext.RouteData.Values["action"].ToString();
            var _control = this.Url.RequestContext.RouteData.Values["controller"].ToString();
            string _activePage = "";
            if (Session["Menu"] != null)
            {
                _activePage = DomainManager.GetEntityToList<COW_MenuListByJsonInquiry_Result>("COW_MenuListByJsonInquiry", null).Where(s => s.ActionMethod == _action && s.Controller == _control).FirstOrDefault().ParentMenuCode.ToString();

                //_activePage = repository.COW_MenuListByJsonInquiry().ToList().Where(s => s.ActionMethod == _action && s.Controller == _control).FirstOrDefault().ParentMenuCode.ToString();
            }
            else
            {
                _activePage = DomainManager.GetEntityToList<COW_MenuListByJsonInquiry_Result>("COW_MenuListByJsonInquiry", null).Where(s => s.ActionMethod == _action && s.Controller == _control).FirstOrDefault().ParentMenuCode.ToString();

                //_activePage = repository.COW_MenuListByJsonInquiry().ToList().Where(s => s.ActionMethod == _action && s.Controller == _control).FirstOrDefault().ParentMenuCode.ToString();
            }

            MenuHistory getMenuLocation = new MenuHistory();
            var a = DomainManager.GetEntityToList<COW_MenuListByJsonInquiry_Result>("COW_MenuListByJsonInquiry", null).ToList();
            List<string> _menuPage = new List<string>(getMenuLocation.GetMenu(_action, _control, _activePage, a));


            //repository.PRW_PlantInquiry().FirstOrDefault().PlantId.ToString()

            Dapper.DynamicParameters parameters01 = new Dapper.DynamicParameters();
            parameters01.Add("@p_PlantId", DomainManager.GetEntityToList<PRW_PlantInquiry_Result>("PRW_PlantInquiry", null).FirstOrDefault().PlantId.ToString());

            SMW_DYP5ViewModel viewModel = new SMW_DYP5ViewModel
            {
                MenuLocation = _menuPage
                ,
                ActivePage = _activePage
                ,
                resourceManager = _resourceManager
                ,
                PRW_PlantInquiry = DomainManager.GetEntityToList<PRW_PlantInquiry_Result>("PRW_PlantInquiry", null).Where(w => w.IsUse == "Y") // repository.PRW_PlantInquiry().Where(w => w.IsUse == "Y")
                ,
                //차종 불러오기.
                SMW_CarTypesInquiry = DomainManager.GetEntityToList<SMW_CarTypesInquiry_Result>("SMW_CarTypesInquiry", parameters01).ToList()  // repository.SMW_CarTypesInquiry(repository.PRW_PlantInquiry().FirstOrDefault().PlantId.ToString()).ToList()
                ,
                //선택된 plantId
                plantId = DomainManager.GetEntityToList<PRW_PlantInquiry_Result>("PRW_PlantInquiry", null).FirstOrDefault().PlantId.ToString() // repository.PRW_PlantInquiry().FirstOrDefault().PlantId.ToString()
                ,
                startDate = DateTime.Today
                ,
                endDate = DateTime.Today
                ,
                //라디오 버튼의 기본값.
                printType = "2"
            };

            return View(viewModel);
        }

        public JsonResult GetCarType(string PlantId)
        {
            Dapper.DynamicParameters parameters01 = new Dapper.DynamicParameters();
            parameters01.Add("@p_PlantId", PlantId);

            var products = DomainManager.GetEntityToList<SMW_CarTypesInquiry_Result>("SMW_CarTypesInquiry", parameters01).ToList(); // repository.SMW_CarTypesInquiry(PlantId).ToList();
            return Json(products, JsonRequestBehavior.AllowGet);
        }
        public ActionResult GetDYP5Result(string plantId, string startDate, string endDate, string carType, string printFlag, DataSourceLoadOptions loadOptions)
        {
            Dapper.DynamicParameters parameters01 = new Dapper.DynamicParameters();
            parameters01.Add("@p_PlantId", plantId);
            parameters01.Add("@p_StartDate", startDate);
            parameters01.Add("@p_EndDate", endDate);
            parameters01.Add("@p_CarType", carType);
            parameters01.Add("@p_PrintFlag", printFlag);

            var result = DataSourceLoader.Load(DomainManager.GetEntityToList<SMW_RankHistorySummaryInquiry_Result>("SMW_RankHistorySummaryInquiry", parameters01), loadOptions);
            var resultJson = JsonConvert.SerializeObject(result);

            return Content(resultJson, "application/json");
        }

        public ActionResult GetDYP5ResultByPart(string plantId, string startDate, string endDate, string carType, string printFlag, string parameter, DataSourceLoadOptions loadOptions)
        {
            Dapper.DynamicParameters parameters01 = new Dapper.DynamicParameters();
            parameters01.Add("@p_PlantId", plantId);
            parameters01.Add("@p_StartDate", startDate);
            parameters01.Add("@p_EndDate", endDate);
            parameters01.Add("@p_CarType", carType);
            parameters01.Add("@p_PrintFlag", printFlag);
            parameters01.Add("@p_Parameter", parameter);

            var result = DataSourceLoader.Load(DomainManager.GetEntityToList<SMW_RankHistorySummaryDPartInquiry_Result>("SMW_RankHistorySummaryDPartInquiry", parameters01), loadOptions);
            var resultJson = JsonConvert.SerializeObject(result);
            return Content(resultJson, "application/json");
        }

        [HttpGet]
        public ActionResult GetDYP5Detail(string plantId, string startDate, string endDate, string carType, string printFlag, string parameter, DataSourceLoadOptions loadOptions)
        {
            Dapper.DynamicParameters parameters01 = new Dapper.DynamicParameters();
            parameters01.Add("@p_PlantId", plantId);
            parameters01.Add("@p_StartDate", startDate);
            parameters01.Add("@p_EndDate", endDate);
            parameters01.Add("@p_CarType", carType);
            parameters01.Add("@p_PrintFlag", printFlag);
            parameters01.Add("@p_Parameter", parameter);

            var result = DataSourceLoader.Load(DomainManager.GetEntityToList<SMW_RankHistorySummaryDRawInquiry_Result>("SMW_RankHistorySummaryDRawInquiry", parameters01), loadOptions);
            var resultJson = JsonConvert.SerializeObject(result);
            return Content(resultJson, "application/json");
        }
        #endregion


    }
}

RecoWeb.WebUI/Views/Delivery/DYP5.cshtml
@model RecoWeb.WebUI.Models.SMW_DYP5ViewModel
@using RecoWeb.Domain.LocalResource

@{

    AjaxOptions ajaxInquiry = new AjaxOptions
    {
        HttpMethod = "GET",
        InsertionMode = InsertionMode.Replace,
        OnSuccess = "ContextInquiry",
        UpdateTargetId = "Context"

    };
}
@*actionName을 가지고 AjaxInquiryContextMenu에
        파라미터로 넘겨주고 비교해 불러올 partialView를 선택하고싶었습니다..T-T 아래와 같은 파라미터를 써서..
    , new { ccc = "DYP5" }*@
@using (Ajax.BeginForm("AjaxInquiryContextMenu", "Delivery", ajaxInquiry))
{
    <div class="row wrapper white-bg page-heading">
        <div class="col-lg-8 col-md-8 col-xs-12" style="display:flex;">
            <span style="float:left; padding:0.6rem; font-size:14px;">
                <i class="fa fa-th" aria-hidden="true"></i>
            </span>
            <div style="align-self:flex-end; padding:0.6rem">

                <ol class="breadcrumb" style="font-size:14px;">
                    @foreach (var page in Model.MenuLocation)
                    {
                        if (page == Model.ActivePage)
                        {
                            <li class="active">
                                <strong>@Model.resourceManager.String("Menu_" + @page) </strong>
                            </li>
                        }
                        else
                        {
                            <li>
                                <span>@Model.resourceManager.String("Menu_" + @page)</span>
                            </li>
                        }
                    }
                </ol>
            </div>
        </div>
        <div class="col-lg-4 col-md-4">
            <div class="btn-group pull-right ">
                @*<button class="btn btn-default" type="submit" id="btn-find1"><i class="fa fa-check"></i>&nbsp;@Resource.Inquiry</button>*@
                <button class="btn bg-primary" type="submit" id="btn-find"><i class="fa fa-check"></i>&nbsp;@Resource.Inquiry</button>
            </div>
        </div>
    </div>
    <div class="row wrapper border-bottom white-bg check-item">
        <div class="btn-group">

            <span class="mr-3">
                <label class="filter-title mr-1">플랜트:</label>
                @Html.DropDownListFor(x => x.PRW_PlantInquiry.FirstOrDefault().PlantName,
                                        new SelectList(Model.PRW_PlantInquiry.Select(s => new SelectListItem { Value = s.PlantId, Text = s.PlantName }), "Value", "Text")
                                        , new { @class = "reco-width-M filter-item", @id = "plant" })
            </span>
            <span>
                <label class="filter-title mr-1">DP일자:</label>
                @Html.TextBoxFor(m => m.startDate, "{0:yyyy-MM-dd}", new { @class = "reco-width_M datepicker filter-item", @data_date_format = "yyyy-mm-dd", @style = "z-index:100; border:solid #A9A9A9 1px;" })
            </span>
            <span class="mr-3">
                <label class="filter-title mr-1">～</label>
                @Html.TextBoxFor(m => m.endDate, "{0:yyyy-MM-dd}", new { @class = "reco-width_M datepicker filter-item", @data_date_format = "yyyy-mm-dd", @style = "z-index:100; border:solid #A9A9A9 1px;" })
            </span>

            <span class="mr-3">
                <label class="filter-title mr-1">서열차종:</label>
                @Html.DropDownListFor(x => x.SMW_CarTypesInquiry.FirstOrDefault().Name,
                                        new SelectList(Model.SMW_CarTypesInquiry.Select(s => new SelectListItem { Value = s.Code, Text = s.Name }), "Value", "Text")
                                        , new { @class = "reco-width-M filter-item", @id = "carType" })
            </span>

            <span class="mr-3">
                <label class="filter-title mr-1">발행:</label>
                <div class="btn-group radios" data-toggle="buttons" style="float:none; margin-bottom:5px;">
                    @Html.RadioButtonFor(x => x.printType, Model.printType == "2" ? "2" : "2", new { @class = (Model.printType == "2" ? "checked=Checked filter-item" : "") })전체
                    @Html.RadioButtonFor(x => x.printType, Model.printType == "1" ? "1" : "1", new { @class = (Model.printType == "1" ? "checked=Checked filter-item" : "") })발행
                    @Html.RadioButtonFor(x => x.printType, Model.printType == "0" ? "0" : "0", new { @class = (Model.printType == "0" ? "checked=Checked filter-item" : "") })미발행
                </div>
            </span>
        </div>
    </div>

}
<div id="Context" class="row wrapper wrapper-content animated fadeInRight" style="background-color:#f3f3f4;">
    @Html.Partial("_DYP5Context")
</div>


@section Styles {
    
}

@section Scripts {

    
    @Scripts.Render("~/bundles/jquery")
    <script src="~/Scripts/plugins/jqGrid/i18n/grid.locale-en.js" type="text/javascript"></script>
    <script src="~/Scripts/plugins/jqGrid/jquery.jqGrid.min.js" type="text/javascript"></script>

    <script type="text/javascript">

        function ContextInquiry(returnValue) {
            var data = returnValue;
            //console.log(data);
        }

        $(document).ready(function () {
            $(':input:checked').parent('.btn').addClass('active');

            // Dropdown list change event.
            $('#plant').change(function () {
                $('#carType option').remove();
                $.getJSON('../Delivery/GetCarType', { PlantId: $('#plant').val() }, function (data) {
                    $.each(data, function () {
                        $('#carType').append('<option value=' +
                          this.Code + '>' + this.Name + '</option>');
                    });
                }).fail(function (jqXHR, textStatus, errorThrown) {
                    console.log(jqXHR);
                    console.log(textStatus);
                    console.log(errorThrown);
                    alert('Error getting products!');
                });
            });

            $('.datepicker').datepicker({
                language: 'ko'
                , autoclose: true
            });
        });
    </script>
}