RecoWeb.Module/Controllers/SystemController.cs
using RecoWeb.Module;
//using RecoWeb.Module.Interfaces;
using RecoWeb.Module.Models;
using RecoWeb.Module.Infrastructure.Concrete;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Net;
using System.Reflection;
using System.Web.Mvc;
using System.Xml;
using RecoWeb.Module.Models.POCO;
using Newtonsoft.Json;
using DevExtreme.AspNet.Mvc;
using DevExtreme.AspNet.Data;

namespace RecoWeb.Module.Controllers
{
    [Authorize]
    public class SystemController : BaseController
    {
        //2018 07 20 by roy (1) : BaseController에서 하단으로 내려옴
        public ResourceWrapper _resourceManager = new ResourceWrapper();

        private DomainConnectionManager DomainManager;
        public SystemController(DomainConnectionManager Domains)
        {
            this.DomainManager = Domains;
        }

        #region 메뉴 편집
        /// <summary>
        /// 메뉴 편집
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult MenuEdit()
        {
            string rmString = _resourceManager.String("ExamplePage");

            var _action = this.Url.RequestContext.RouteData.Values["action"].ToString();
            var _control = this.Url.RequestContext.RouteData.Values["controller"].ToString();
            string _activePage = "";
            if (Session["Menu"] != null)
            {
                _activePage = DomainManager.GetEntityToList<COW_MenuListByJsonInquiry_Result>("COW_MenuListByJsonInquiry", null).Where(s => s.ActionMethod == _action && s.Controller == _control).FirstOrDefault().ParentMenuCode.ToString();
            }
            else
            {
                _activePage = DomainManager.GetEntityToList<COW_MenuListByJsonInquiry_Result>("COW_MenuListByJsonInquiry", null).Where(s => s.ActionMethod == _action && s.Controller == _control).FirstOrDefault().ParentMenuCode.ToString();
            }

            MenuHistory getMenuLocation = new MenuHistory();
            List<string> _menuPage = new List<string>(getMenuLocation.GetMenu(_action, _control, _activePage, DomainManager.GetEntityToList<COW_MenuListByJsonInquiry_Result>("COW_MenuListByJsonInquiry", null).ToList()));


            Dapper.DynamicParameters parameters01 = new Dapper.DynamicParameters();
            parameters01.Add("@p_IsUse", true);

            Dapper.DynamicParameters parameters02 = new Dapper.DynamicParameters();
            parameters02.Add("@p_IsUse", true);
            parameters02.Add("@p_ParentMenuCode", "");

            COW_MenuListInquiryViewModel viewModel = new COW_MenuListInquiryViewModel
            {
                COW_RootMenuListInquiry = DomainManager.GetEntityToList<COW_RootMenuListInquiry_Result>("COW_RootMenuListInquiry", parameters01).ToList()
                ,
                COW_SubMenuListInquiry = DomainManager.GetEntityToList<COW_SubMenuListInquiry_Result>("COW_SubMenuListInquiry", parameters02).ToList()
                ,
                MenuLocation = _menuPage
                ,
                ActivePage = _activePage
                ,
                isUse = true
                ,
                resourceManager = _resourceManager
            };

            return View(viewModel);
        }

        public PartialViewResult AjaxInquiryContextMenu()
        {
            return PartialView("_MenuEditContext");
        }

        [HttpGet]
        public JsonResult GetLargeMenu(bool isUse)
        {
            Dapper.DynamicParameters parameters01 = new Dapper.DynamicParameters();
            parameters01.Add("@p_IsUse", isUse);

            COW_MenuListInquiryViewModel viewModel = new COW_MenuListInquiryViewModel
            {
                COW_RootMenuListInquiry = DomainManager.GetEntityToList<COW_RootMenuListInquiry_Result>("COW_RootMenuListInquiry", parameters01)
            };

            return Json(viewModel.COW_RootMenuListInquiry, JsonRequestBehavior.AllowGet);

            //var result = DataSourceLoader.Load(DomainManager.GetEntityToList<COW_RootMenuListInquiry_Result>("COW_RootMenuListInquiry", parameters01), loadOptions);
            //var resultJson = JsonConvert.SerializeObject(result);
            //return Content(resultJson, "application/json");
        }

        [HttpGet]
        public ActionResult GetMediumMenu(bool isUse, string largeMenuCode)//, DataSourceLoadOptions loadOptions)
        {
            Dapper.DynamicParameters parameters01 = new Dapper.DynamicParameters();
            parameters01.Add("@p_IsUse", isUse);
            parameters01.Add("@p_ParentMenuCode", largeMenuCode);

            COW_MenuListInquiryViewModel viewModel = new COW_MenuListInquiryViewModel
            {
                COW_SubMenuListInquiry = DomainManager.GetEntityToList<COW_SubMenuListInquiry_Result>("COW_SubMenuListInquiry", parameters01)
            };

            return Json(viewModel.COW_SubMenuListInquiry, JsonRequestBehavior.AllowGet);

            //var result = DataSourceLoader.Load(DomainManager.GetEntityToList<COW_SubMenuListInquiry_Result>("COW_SubMenuListInquiry", parameters01), loadOptions);
            //var resultJson = JsonConvert.SerializeObject(result);
            //return Content(resultJson, "application/json");
        }

        [HttpGet]
        public ActionResult GetSmallMenu(bool isUse, string mediumParentMenuCode)//, DataSourceLoadOptions loadOptions)
        {
            Dapper.DynamicParameters parameters01 = new Dapper.DynamicParameters();
            parameters01.Add("@p_IsUse", isUse);
            parameters01.Add("@p_ParentMenuCode", mediumParentMenuCode);

            COW_MenuListInquiryViewModel viewModel = new COW_MenuListInquiryViewModel
            {
                COW_SubMenuListInquiry = DomainManager.GetEntityToList<COW_SubMenuListInquiry_Result>("COW_SubMenuListInquiry", parameters01)
            };

            return Json(viewModel.COW_SubMenuListInquiry, JsonRequestBehavior.AllowGet);
            //주섟풀기
            //var result = DataSourceLoader.Load(DomainManager.GetEntityToList<COW_SubMenuListInquiry_Result>("COW_SubMenuListInquiry", parameters01), loadOptions);
            //var resultJson = JsonConvert.SerializeObject(result);
            //return Content(resultJson, "application/json");
        }

        [HttpPost]
        public string RootCreate([Bind(Exclude = "Id")] COW_RootMenuListInquiry_Result obj)
        {

            string msg;

            Dapper.DynamicParameters parameters01 = new Dapper.DynamicParameters();
            parameters01.Add("@p_MenuCode", obj.MenuCode);
            parameters01.Add("@p_MenuName", obj.MenuName);
            parameters01.Add("@p_Description", obj.Description);
            parameters01.Add("@p_Sequence", Convert.ToInt32(obj.Sequence));
            parameters01.Add("@p_ParentMenuCode", "Root");
            parameters01.Add("@p_Category", obj.Category);
            parameters01.Add("@p_Controller", obj.Controller);
            parameters01.Add("@p_ActionMethod", obj.ActionMethod);
            parameters01.Add("@p_Icon", obj.IconValue);
            parameters01.Add("@p_IsUse", Convert.ToBoolean(Convert.ToInt16(obj.IsUse)));
            parameters01.Add("@p_UserName", HttpContext.User.Identity.Name);
            parameters01.Add("@p_OutMessage", dbType: DbType.String, direction: ParameterDirection.Output, size: 5215585);

            try
            {
                if (ModelState.IsValid)
                {
                    var returnParameter = DomainManager.GetEntityResult("COW_MenuListSave", parameters01);

                    if (parameters01.Get<string>("@p_OutMessage").ToString() == "OK")
                        msg = "Saved Successfully";
                    else
                        msg = parameters01.Get<string>("@p_OutMessage").ToString();
                }
                else
                {
                    msg = "Validation data not successfull";
                }
                return msg;
                //return new HttpStatusCodeResult(HttpStatusCode.Created);
            }
            catch (Exception ex)
            {
                msg = "Error occured:" + ex.Message;
                return msg;
                //return new HttpStatusCodeResult(HttpStatusCode.Created);
            }
        }



        public string RootEdit(COW_RootMenuListInquiry_Result obj, string id)
        {
            string msg;
            Dapper.DynamicParameters parameters01 = new Dapper.DynamicParameters();
            parameters01.Add("@p_MenuCode", obj.MenuCode);
            parameters01.Add("@p_MenuName", obj.MenuName);
            parameters01.Add("@p_Description", obj.Description);
            parameters01.Add("@p_Sequence", Convert.ToInt32(obj.Sequence));
            parameters01.Add("@p_ParentMenuCode", obj.ParentMenuCode);
            parameters01.Add("@p_Category", obj.Category);
            parameters01.Add("@p_Controller", obj.Controller);
            parameters01.Add("@p_ActionMethod", obj.ActionMethod);
            parameters01.Add("@p_Icon", obj.IconValue);
            parameters01.Add("@p_IsUse", Convert.ToBoolean(Convert.ToInt16(obj.IsUse)));
            parameters01.Add("@p_UserName", HttpContext.User.Identity.Name);
            parameters01.Add("@p_OutMessage", dbType: DbType.String, direction: ParameterDirection.Output, size: 5215585);

            try
            {
                if (ModelState.IsValid)
                {
                    var returnParameter = DomainManager.GetEntityResult("COW_MenuListSave", parameters01);

                    if (parameters01.Get<string>("@p_OutMessage").ToString() == "OK")
                        msg = "Saved Successfully";
                    else
                        msg = parameters01.Get<string>("@p_OutMessage").ToString();
                }
                else
                {
                    msg = "Validation data not successfull";
                }
                return msg;

RecoWeb.Module/Views/System/Preferences.cshtml
@model RecoWeb.Module.Models.PreferencesViewModel
@using RecoWeb.Domain.LocalResource

<div id="Context" class="row wrapper wrapper-content animated fadeInRight">
    <div class="col-lg-3 col-md-3">
        @using (Html.BeginForm("TitleSave", "System", new { title = Model.Title }, FormMethod.Get, new { role = "form" }))
        {
            <div class="ibox">
                <div class="ibox-title">
                    <span style="font-size:1.4rem;"><i class="fa fa-list-alt" aria-hidden="true"></i>&nbsp;사이트정보</span>
                </div>
                <div class="ibox-content">
                    <p>사이트명:</p>
                    @Html.TextBoxFor(x => x.Title)
                    <button type="submit" class="btn btn-primary">
                        저장
                    </button>
                </div>

            </div>
        }

    </div>

    <div class="col-lg-3 col-md-3">
        @using (Html.BeginForm("RecentVisitSave", "System", new { title = Model.RecentVisit }, FormMethod.Get, new { role = "form" }))
        {
            <div class="ibox">
                <div class="ibox-title">
                    <span style="font-size:1.4rem;"><i class="fa fa-list-ul" aria-hidden="true"></i>&nbsp;화면정보</span>
                </div>
                <div class="ibox-content">
                    <p>최근 방문 페이지 개수:</p>
                    @Html.TextBoxFor(x => x.RecentVisit)
                    <button type="submit" class="btn btn-primary">
                        저장
                    </button>
                </div>
            </div>
        }
    </div>
    <div class="col-lg-3 col-md-3">

        @*배포시 Footer Fixed의 초기값은 반드시 false로 해야함.*@
        @*└> 이유: true/false로 변경시에 fixed라는 클래스를 추가/제거해주는 구문이 들어감.*@
        @using (Html.BeginForm("FooterFixedSave", "System", new { title = Model.isFooterFixed }, FormMethod.Get, new { role = "form" }))
        {
            <div class="ibox">
                <div class="ibox-title">
                    <span style="font-size:1.4rem;"><i class="fa fa-list-ul" aria-hidden="true"></i>&nbsp;설정</span>
                </div>
                <div class="ibox-content">
                    <p>Footer Fixed:</p>
                    @Html.CheckBoxFor(x => x.isFooterFixed, new { @data_toggle = "toggle", @data_on = "Yes", @data_off = "No", @checked = true, @data_size = "normal" })
                    <input type="submit" id="footer-save" class="btn btn-primary" value="저장" />
                </div>
            </div>
        }
    </div>
    <div class="col-lg-3 col-md-3">
        <div>
            @using (Html.BeginForm("BackgoundSave", "System", FormMethod.Post, new { id = "form-Background" }))
            {
                <div class="ibox">
                    <div class="ibox-title">
                        <span style="font-size:1.4rem;"><i class="fa fa-list-ul" aria-hidden="true"></i>&nbsp;로그인화면</span>
                    </div>
                    <div class="ibox-content">
                        <p>로그인화면 설정</p>
                        <div style="display:flex;">
                            <input type="file" id="background-files" class="backgound-file" name="postedFile">
                            <input type="button" id="background-save" class="btn btn-primary" value="저장" />
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

@section Styles {
    <link href="@Url.Action("plugins/bootstrap-toggle/bootstrap-toggle.min.css", "Content")" rel="stylesheet" type="text/css" />
    <link href="@Url.Action("plugins/sweetalert/sweetalert.css", "Content")" rel="stylesheet" type="text/css" />

}

@section Scripts {
    <script src="../Scripts/jquery-3.1.1.min.js"></script>
    <script src="../Scripts/plugins/bootstrap-toggle/bootstrap-toggle.min.js" type="text/javascript"></script>
    <script src="../Scripts/plugins/sweetalert/sweetalert.min.js" type="text/javascript"></script>


    <script type="text/javascript">
        $().ready(function () {

            //Footer Fixed Toggle 이벤트
            $('#isFooterFixed').on('change', function () {
                $('#isFooterFixed').val($(this).prop('checked'));
            });
            //Footer Fixed 저장버튼 클릭
            $('#footer-save').on('click', function () {
                if ($('#isFooterFixed').prop('checked')) {
                    console.log('on');
                    localStorage.setItem('fixedfooter', 'on');
                } else {
                    console.log('off');
                    localStorage.setItem('fixedfooter', 'off');
                }
            });

            //배경화면 저장버튼 클릭
            $('#background-save').on("click", function () {
                var filesss = $(".backgound-file")[0];
                if (filesss !== undefined) {
                    var filea = filesss.files[0];

                    if (filea == undefined) {
                        swal({
                            title: "알림",
                            text: "파일을 선택하세요.",
                            type: "warning"
                        });
                        return;
                    }
                    if (filea.size > 20971520) {
                        swal({
                            title: "알림",
                            text: "파일 크기는 20MB이하 입니다.",
                            type: "warning"
                        });
                        return;
                    }
                    var imgTypes, inputFileName;
                    inputFileName = filesss.files[0].name;
                    if (inputFileName.split('.').length != 2) {
                        swal({
                            title: "알림",
                            text: "파일 이름이 잘못되었습니다.",
                            type: "warning"
                        });
                        return;
                    }

                    imgTypes = inputFileName.split('.')[1];
                    if (imgTypes != 'jpg' && imgTypes != 'jepg' && imgTypes != 'png' && imgTypes != 'gif' && imgTypes != 'bmp') {
                        swal({
                            title: "알림",
                            text: "파일을 형식이 잘못되었습니다.",
                            type: "warning"
                        });
                        return;
                    }

                    var reader = new FileReader();
                    reader.readAsDataURL(filea);
                    reader.onload = function () {
                        result = reader.result;
                        result = result.replace(/\+/g, '_');

                        $.ajax({
                            url: '../System/BackgoundSave',

                            //파일 이름은 index.jpg로 고정
                            data: "&fileData=" + result + "&file=" + "index.jpg",

                            processData: false,
                            contentType: "application/x-www-form-urlencoded; charset=UTF-8",
                            type: 'POST',
                            success: function (data) {
                                swal({
                                    title: "알림",
                                    text: "업로드 완료",
                                    type: "success",
                                    showCancelButton: false,
                                    confirmButtonClass: "confirm",
                                    confirmButtonText: "OK",
                                    closeOnConfirm: false
                                }, function (isConfirm) {
                                    //성공시 새로고침
                                    if (isConfirm) {
                                        location.reload(true);
                                    }
                                });

                            },
                            error: function (request, status, error) {
                                console.log("code:" + request.status + "\n" + "message:" + request.responseText + "\n" + "error:" + error);
                                swal({
                                    title: "알림",
                                    text: "업로드 실패",
                                    type: "error"
                                });
                                return;
                            }
                        });
                    }
                }
            });

        });

    </script>
}

RecoWeb.Module/Views/System/_Permissions.cshtml
@model RecoWeb.Module.Models.PermissionViewModel
@using RecoWeb.Domain.LocalResource

<div class="col-lg-5 col-md-5 h-100">
    <div class="ibox">
        <div class="ibox-title">
            <span style="font-size:1.4rem;"><i class="fa fa-list-alt" aria-hidden="true"></i>&nbsp;메뉴</span>
        </div>
        <div class="ibox-content">
            @(Html.DevExtreme().TreeList()
                    .ID("gridContainer01")
                    .KeyExpr("Id")
                    .ParentIdExpr("ParentId")
                    //.DataSource(new JS("menuList"))
                    .DataSource(ds => ds.Mvc().Controller("System").Key("Id")
                        .LoadAction("GetCOW_PermissionMenuInquiry")
                        .LoadParams(new
                        {
                            userId = ""
                        }
                        )
                    )
                    .Columns(columns =>
                    {
                        columns.Add().DataField("MenuCode").Caption("메뉴").Alignment(HorizontalAlignment.Left);

                        columns.Add().DataField("Description").Caption("설명").Alignment(HorizontalAlignment.Left);

                        columns.Add().DataField("IsUse").Caption("사용여부").Alignment(HorizontalAlignment.Center);

                        columns.Add().DataField("Sequence").Caption("순서").Alignment(HorizontalAlignment.Right);

                        columns.Add().DataField("ParentMenuCode").Caption("A").Alignment(HorizontalAlignment.Center).Visible(false);

                        columns.Add().DataField("TreeLevel").Caption("B").Alignment(HorizontalAlignment.Left).Visible(false);
                        columns.Add().DataField("IsLeaf").Caption("C").Alignment(HorizontalAlignment.Left).Visible(false);
                        columns.Add().DataField("Loaded").Caption("D").Alignment(HorizontalAlignment.Left).Visible(false);
                        columns.Add().DataField("Expanded").Caption("E").Alignment(HorizontalAlignment.Left).Visible(false);
                        columns.Add().DataField("_KeyColumn").Caption("키").Alignment(HorizontalAlignment.Left).Visible(false);
                    })
                    .ShowRowLines(true)
                    .ShowColumnLines(true)
                    .ShowBorders(true)
                    .ColumnAutoWidth(true)
                    .ExpandedRowKeys(new[] { 1 })
                    .HoverStateEnabled(true)
                    .Selection(e => e.Mode(SelectionMode.Single))
                    .OnSelectionChanged("tree1Change") //체인지 이벤트를 선언함
                    .OnContentReady("onReady") // 레디 이벤트
            )
        </div>
    </div>
</div>

<div class="col-lg-7 col-md-7 h-100">
    <div>
        <div class="ibox">
            <div class="ibox-title">
                <span style="font-size:1.4rem;"><i class="fa fa-list-ul" aria-hidden="true"></i>&nbsp;역할권한</span>
                <span class="pull-right">
                    <button type="button" class="btn btn-default ibox-title-btn" id="btnCreateRole">추가</button>
                    <button type="button" class="btn btn-default ibox-title-btn" id="btnReadRole">읽기</button>
                    <button type="button" class="btn btn-default ibox-title-btn" id="btnUpdateRole">수정</button>
                    <button type="button" class="btn btn-default ibox-title-btn" id="btnDeleteRole">삭제</button>
                    <button type="button" class="btn btn-default ibox-title-btn" id="btnNoAuthRole">권한없음</button>
                    <button type="button" class="btn btn-default view-modal ibox-title-btn" id="btnAddRole" data-toggle='modal' data-target='#Modals'>역할추가</button>
                    <button type="button" class="btn btn-default ibox-title-btn" id="btnRemoveRole">역할삭제</button>
                </span>

            </div>
            <div class="ibox-content">
                @(Html.DevExtreme().DataGrid()
                    .ID("gridContainer02")
                    .Paging(paging => paging.PageSize(20))
                    .Pager(pager =>
                    {
                        pager.ShowPageSizeSelector(true);
                        pager.AllowedPageSizes(new List<int> { 20, 50, 100, 200, 300, 500 });
                        pager.ShowInfo(true);
                    })
                    .Export(e => e.Enabled(true).FileName("ExportTest").AllowExportSelectedData(true))  //Export
                    .ColumnAutoWidth(true)
                    .ShowColumnLines(true)
                    .ShowRowLines(true)
                    .ShowBorders(true)
                    .HoverStateEnabled(true)
                    .Sorting(e => e.Mode(GridSortingMode.Multiple))
                    .ColumnMinWidth(50)
                    .AllowColumnResizing(true)
                    .Option("columnResizingMode", ColumnResizingMode.Widget)
                    .Columns(columns =>
                    {
                        columns.Add().DataField("RoleId").Caption("역할코드").Alignment(HorizontalAlignment.Left);
                        columns.Add().DataField("RoleName").Caption("역할이름").Alignment(HorizontalAlignment.Left);
                        columns.Add().DataField("MenuCode").Caption("메뉴코드").Alignment(HorizontalAlignment.Left);
                        columns.Add().DataField("AuthCreate").Caption("추가").Alignment(HorizontalAlignment.Center);
                        columns.Add().DataField("AuthRead").Caption("읽기").Alignment(HorizontalAlignment.Center);
                        columns.Add().DataField("AuthUpdate").Caption("수정").Alignment(HorizontalAlignment.Center);
                        columns.Add().DataField("AuthDelete").Caption("삭제").Alignment(HorizontalAlignment.Center);
                        columns.Add().DataField("C_KeyColumn").Caption("키").Alignment(HorizontalAlignment.Left).Visible(false);
                    })
                    .Editing(e => e.Mode(GridEditMode.Popup)
                            .AllowAdding(true)
                            .AllowUpdating(true)
                            .AllowDeleting(true)
                            .UseIcons(true)
                            .Popup(p => p
                                    .ShowTitle(true)
                                    .Width(800)
                                    .Height(550)
                                    .Position(pos => pos
                                            .My(HorizontalAlignment.Center, VerticalAlignment.Center)
                                            .At(HorizontalAlignment.Center, VerticalAlignment.Center)
                                            .Of(new JS("window"))
                                            )
                                )
                            )
                    .Height(new JS("heightCalc('50')"))
                    .Selection(e => e.Mode(SelectionMode.Multiple))
                )
            </div>
        </div>
    </div>

    <div>
        <div class="ibox">
            <div class="ibox-title">
                <span style="font-size:1.4rem;"><i class="fa fa-th-list" aria-hidden="true"></i>&nbsp;작업자권한</span>
                <span class="pull-right">
                    <button type="button" class="btn btn-default ibox-title-btn" id="btnCreateEmployee">추가</button>
                    <button type="button" class="btn btn-default ibox-title-btn" id="btnReadEmployee">읽기</button>
                    <button type="button" class="btn btn-default ibox-title-btn" id="btnUpdateEmployee">수정</button>
                    <button type="button" class="btn btn-default ibox-title-btn" id="btnDeleteEmployee">삭제</button>
                    <button type="button" class="btn btn-default ibox-title-btn" id="btnNoAuthEmployee">권한없음</button>
                    <button type="button" class="btn btn-default view-modal ibox-title-btn" id="btnAddEmployee" data-toggle='modal' data-target='#ModalsEmployee'>작업자추가</button>
                    <button type="button" class="btn btn-default ibox-title-btn" id="btnRemoveEmployee">작업자삭제</button>
                </span>
            </div>
            <div class="ibox-content">
                @(Html.DevExtreme().DataGrid()
                    .ID("gridContainer03")
                    .Paging(paging => paging.PageSize(20))
                    .Pager(pager =>
                    {
                        pager.ShowPageSizeSelector(true);
                        pager.AllowedPageSizes(new List<int> { 20, 50, 100, 200, 300, 500 });
                        pager.ShowInfo(true);
                    })
                    .Export(e => e.Enabled(true).FileName("ExportTest").AllowExportSelectedData(true))  //Export
                    .ColumnAutoWidth(true)
                    .ShowColumnLines(true)
                    .ShowRowLines(true)
                    .ShowBorders(true)
                    .HoverStateEnabled(true)
                    .Sorting(e => e.Mode(GridSortingMode.Multiple))
                    .ColumnMinWidth(50)
                    .AllowColumnResizing(true)
                    .Option("columnResizingMode", ColumnResizingMode.Widget)
                    .Columns(columns =>
                    {
                        columns.Add().DataField("EmployeeId").Caption("작업자코드").Alignment(HorizontalAlignment.Left);
                        columns.Add().DataField("EmployeeName").Caption("작업자이름").Alignment(HorizontalAlignment.Left);
                        columns.Add().DataField("MenuCode").Caption("메뉴코드").Alignment(HorizontalAlignment.Left);
                        columns.Add().DataField("AuthCreate").Caption("추가").Alignment(HorizontalAlignment.Center);
                        columns.Add().DataField("AuthRead").Caption("읽기").Alignment(HorizontalAlignment.Center);
                        columns.Add().DataField("AuthUpdate").Caption("수정").Alignment(HorizontalAlignment.Center);
                        columns.Add().DataField("AuthDelete").Caption("삭제").Alignment(HorizontalAlignment.Center);
                        columns.Add().DataField("C_KeyColumn").Caption("키").Alignment(HorizontalAlignment.Left).Visible(false);
                    })
                    .Height(new JS("heightCalc('50')"))
                    .Selection(e => e.Mode(SelectionMode.Multiple))
                )
            </div>
        </div>
    </div>
</div>


@section Styles {
    <link href="@Url.Action("plugins/bootstrap-toggle/bootstrap-toggle.min.css", "Content")" rel="stylesheet" type="text/css" />

    <link href="@Url.Action("plugins/sweetalert/sweetalert.css", "Content")" rel="stylesheet" type="text/css" />

}

<script type="text/javascript">
    var row_grid1;

    //그리드 Load이후 타는 이벤트
    function onReady(a) {
        if ($('#gridContainer01').dxTreeList("instance").totalCount() > 0) {
            $('#gridContainer01').dxTreeList("instance").selectRowsByIndexes(0);
            //↑ 동일함. (↓더 많은 테스트는 진행못함)
            //$('#' + a.element[0].id).dxDataGrid("instance").selectRows(1)
        }
    }

    function getAllSelectOptions() {
        var states = {};
        states = { "Administrator": "관리자", "Developer": "개발자", "Executives": "임원", "Master": "마스터", "Production": "생산", "Qulity": "품질", "Worker": "작업자" };
        $.post('../Common/GetCOW_CodeRolesInquiry', null, function (data) {
            var userDetails = {};
            $.each(data, function () {
                userDetails[this.RoleId] = this.RoleName;
            })
            states = userDetails;
        }).fail(function (jqXHR, textStatus, errorThrown) {
            alert('Error getting products!');
        });
        return states;
    }

</script>